### ISSUE TITLE
High addon CPU usage

### ISSUE THREAD

**Issue by GeekAndProud** [kstange/MasqueBlizzBars#2]
https://i.imgur.com/WNHowG9.png, seems to be caused by bars being shown/hidden(TellMeWhen)causing a spike in addon usage.

**Comment by kstange** [comment]
When I picked this up from the existing author it had a hook on UIParent_ManageFramePositions which I just assumed to be necessary, but it doesn't seem to be.  This will be gone in 2.0.1 (commit 43d110a) and should fix the problem.
